<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\PerfilRestaurante;
use App\Models\Restaurante;
use App\Models\Usuario;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class RestauranteSeeder extends Seeder
{
    public function run(): void
    {
        $categorias = Categoria::pluck('id', 'nombre_categoria');

        foreach ($this->restaurantData() as $data) {
            $slug = str($data['nombre'])->slug('');

            $usuario = Usuario::create([
                'nombre'   => 'Dueño ' . $data['nombre'],
                'email'    => 'contacto@' . $slug . '.com',
                'password' => Hash::make('password'),
                'telefono' => $data['telefono'],
                'estado'   => 'activo',
                'rol_id'   => 2,
            ]);

            PerfilRestaurante::create([
                'usuario_id' => $usuario->id,
                'nit'        => (string) random_int(1000000, 9999999),
            ]);

            $restaurante = Restaurante::create([
                'usuario_id'             => $usuario->id,
                'nombre'                 => $data['nombre'],
                'descripcion'            => $data['descripcion'],
                'direccion'              => $data['direccion'],
                'zona'                   => $data['zona'],
                'latitud'                => $data['latitud'],
                'longitud'               => $data['longitud'],
                'telefono'               => $data['telefono'],
                'email_reservas'         => $data['email_reservas'],
                'instagram'              => $data['instagram'],
                'facebook_url'           => $data['facebook_url'],
                'horario_apertura'       => $data['horario_apertura'],
                'horario_cierre'         => $data['horario_cierre'],
                'hora_apertura_sabado'   => $data['hora_apertura_sabado'],
                'hora_cierre_sabado'     => $data['hora_cierre_sabado'],
                'hora_apertura_domingo'  => $data['hora_apertura_domingo'],
                'hora_cierre_domingo'    => $data['hora_cierre_domingo'],
                'foto_portada'           => $data['foto_portada'],
                'logo_url'               => $data['logo_url'] ?? null,
                'fecha_registro'         => $data['fecha_registro'],
                'estado'                 => 'activo',
                'es_principal'           => true,
            ]);

            $catIds = collect($data['categorias'])
                ->map(fn($name) => $categorias[$name] ?? null)
                ->filter()
                ->values()
                ->toArray();

            if (!empty($catIds)) {
                $restaurante->categorias()->attach($catIds);
            }
        }

        $this->command->info('50 restaurantes sembrados correctamente.');
    }

    private function restaurantData(): array
    {
        return [
            // ==================== GLOBAL BRANDS (12) ====================
            [
                'nombre' => 'McDonald\'s',
                'descripcion' => 'La cadena de comida rápida más famosa del mundo. Especializada en hamburguesas, papas fritas y el icónico Big Mac.',
                'direccion' => 'Av. Ballivián Nro. 500, Centro Comercial Megacenter',
                'zona' => 'Zona Sur',
                'latitud' => -16.5402, 'longitud' => -68.0735,
                'telefono' => '72534101', 'email_reservas' => 'reservas@mcdonaldslapaz.com',
                'instagram' => '@mcdonalds_bo', 'facebook_url' => 'facebook.com/McDonaldsBolivia',
                'horario_apertura' => '08:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '08:00', 'hora_cierre_sabado' => '00:00',
                'hora_apertura_domingo' => '09:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900',
                'logo_url' => 'https://upload.wikimedia.org/wikipedia/commons/3/36/McDonald%27s_Golden_Arches.svg',
                'fecha_registro' => '2024-01-15', 'categorias' => ['Burgers'],
            ],
            [
                'nombre' => 'Starbucks',
                'descripcion' => 'La reconocida cadena internacional de café de especialidad. Ambiente acogedor con variedad de bebidas calientes y frías.',
                'direccion' => 'Av. Montenegro Nro. 135, Zona Sur',
                'zona' => 'Zona Sur',
                'latitud' => -16.5385, 'longitud' => -68.0702,
                'telefono' => '72534102', 'email_reservas' => 'lapaz@starbucks.com.bo',
                'instagram' => '@starbucks_bolivia', 'facebook_url' => 'facebook.com/StarbucksBolivia',
                'horario_apertura' => '07:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '08:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '09:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
                'logo_url' => '/seed-logos/starbucks.svg',
                'fecha_registro' => '2024-02-10', 'categorias' => ['Café y Brunch'],
            ],
            [
                'nombre' => 'Burger King',
                'descripcion' => 'Famosos por la parrilla de fuego real y la Whopper. Comida rápida con sabor a carbón.',
                'direccion' => 'Calle Capitán Ravelo Nro. 210, Sopocachi',
                'zona' => 'Sopocachi',
                'latitud' => -16.5075, 'longitud' => -68.1298,
                'telefono' => '72534103', 'email_reservas' => 'contacto@burgerkinglapaz.com',
                'instagram' => '@burgerkingbo', 'facebook_url' => 'facebook.com/BurgerKingBolivia',
                'horario_apertura' => '09:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '09:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '10:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900',
                'logo_url' => '/seed-logos/burger_king.svg',
                'fecha_registro' => '2024-03-05', 'categorias' => ['Burgers'],
            ],
            [
                'nombre' => 'KFC',
                'descripcion' => 'Kentucky Fried Chicken, la casa del pollo frito con la receta secreta de 11 hierbas y especias.',
                'direccion' => 'Av. 16 de Julio Nro. 1500, El Prado',
                'zona' => 'Centro',
                'latitud' => -16.4965, 'longitud' => -68.1342,
                'telefono' => '72534104', 'email_reservas' => 'reservas@kfclapaz.com',
                'instagram' => '@kfc_bolivia', 'facebook_url' => 'facebook.com/KFCBolivia',
                'horario_apertura' => '10:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '10:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '11:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=900',
                'logo_url' => '/seed-logos/kfc.svg',
                'fecha_registro' => '2024-03-20', 'categorias' => ['Pollos'],
            ],
            [
                'nombre' => 'Pizza Hut',
                'descripcion' => 'Pizzería internacional con masa tradicional y pan de ajo. Perfecta para compartir en familia.',
                'direccion' => 'Av. Sánchez Bustamante Nro. 250, Sopocachi',
                'zona' => 'Sopocachi',
                'latitud' => -16.5050, 'longitud' => -68.1275,
                'telefono' => '72534105', 'email_reservas' => 'lapaz@pizzahut.com.bo',
                'instagram' => '@pizzahutbolivia', 'facebook_url' => 'facebook.com/PizzaHutBolivia',
                'horario_apertura' => '11:00', 'horario_cierre' => '22:30',
                'hora_apertura_sabado' => '11:00', 'hora_cierre_sabado' => '23:30',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=900',
                'logo_url' => '/seed-logos/pizza_hut.svg',
                'fecha_registro' => '2024-04-01', 'categorias' => ['Pizza'],
            ],
            [
                'nombre' => 'Domino\'s Pizza',
                'descripcion' => 'Pizza rápida con entrega garantizada en 30 minutos. Amplia variedad de toppings y acompañamientos.',
                'direccion' => 'Calle 15 Nro. 50, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5398, 'longitud' => -68.0695,
                'telefono' => '72534106', 'email_reservas' => 'pedidos@dominoslapaz.com',
                'instagram' => '@dominos_bolivia', 'facebook_url' => 'facebook.com/DominosBolivia',
                'horario_apertura' => '11:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '11:00', 'hora_cierre_sabado' => '00:00',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://upload.wikimedia.org/wikipedia/commons/9/91/Pizza-3007395.jpg',
                'logo_url' => '/seed-logos/dominos.svg',
                'fecha_registro' => '2024-04-15', 'categorias' => ['Pizza'],
            ],
            [
                'nombre' => 'Subway',
                'descripcion' => 'Sándwiches submarinos personalizados con ingredientes frescos. Opciones saludables para todos.',
                'direccion' => 'Av. Arce Nro. 450, Edificio Montevideo',
                'zona' => 'Centro',
                'latitud' => -16.5020, 'longitud' => -68.1310,
                'telefono' => '72534107', 'email_reservas' => 'contacto@subwaylapaz.com',
                'instagram' => '@subway_bolivia', 'facebook_url' => 'facebook.com/SubwayBolivia',
                'horario_apertura' => '09:00', 'horario_cierre' => '21:00',
                'hora_apertura_sabado' => '09:00', 'hora_cierre_sabado' => '22:00',
                'hora_apertura_domingo' => '10:00', 'hora_cierre_domingo' => '20:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900',
                'logo_url' => '/seed-logos/subway.svg',
                'fecha_registro' => '2024-05-01', 'categorias' => ['Burgers'],
            ],
            [
                'nombre' => 'Papa John\'s',
                'descripcion' => 'Pizza artesanal con masa fresca y salsa de tomate original. Ingredientes premium.',
                'direccion' => 'Calle 21 Nro. 789, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5410, 'longitud' => -68.0720,
                'telefono' => '72534108', 'email_reservas' => 'pedidos@papajohnslapaz.com',
                'instagram' => '@papajohnsbo', 'facebook_url' => 'facebook.com/PapaJohnsBolivia',
                'horario_apertura' => '11:00', 'horario_cierre' => '22:30',
                'hora_apertura_sabado' => '11:00', 'hora_cierre_sabado' => '23:30',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=900',
                'logo_url' => '/seed-logos/papa_johns.svg',
                'fecha_registro' => '2024-05-15', 'categorias' => ['Pizza'],
            ],
            [
                'nombre' => 'Hard Rock Cafe',
                'descripcion' => 'Rock & roll, hamburguesas legendarias y un ambiente eléctrico. Icono mundial de la comida estadounidense.',
                'direccion' => 'Calle 8 Nro. 100, Obrajes',
                'zona' => 'Zona Sur',
                'latitud' => -16.5330, 'longitud' => -68.0765,
                'telefono' => '72534109', 'email_reservas' => 'lapaz@hardrockcafe.com',
                'instagram' => '@hardrockcafelapaz', 'facebook_url' => 'facebook.com/HardRockCafeLaPaz',
                'horario_apertura' => '12:00', 'horario_cierre' => '00:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '02:00',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '23:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900',
                'logo_url' => 'https://upload.wikimedia.org/wikipedia/commons/5/56/Hard_Rock_Cafe_logo.svg',
                'fecha_registro' => '2024-06-01', 'categorias' => ['Burgers'],
            ],
            [
                'nombre' => 'TGI Fridays',
                'descripcion' => 'Restaurante casual con ambiente festivo, costillas BBQ, nachos y cócteles icónicos.',
                'direccion' => 'Av. Montenegro Nro. 500, San Miguel',
                'zona' => 'Zona Sur',
                'latitud' => -16.5430, 'longitud' => -68.0740,
                'telefono' => '72534110', 'email_reservas' => 'reservas@tgifridayslapaz.com',
                'instagram' => '@tgifridays_bo', 'facebook_url' => 'facebook.com/TGIFridaysBolivia',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '01:00',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900',
                'logo_url' => 'https://upload.wikimedia.org/wikipedia/commons/a/aa/T.G.I._Friday%27s_logo.svg',
                'fecha_registro' => '2024-06-15', 'categorias' => ['Cocina Fusión'],
            ],
            [
                'nombre' => 'Chili\'s',
                'descripcion' => 'Tex-Mex y comida americana en un ambiente relajado. Fajitas, costillas y la famosa salsa chili.',
                'direccion' => 'Calle 17 Nro. 350, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5405, 'longitud' => -68.0710,
                'telefono' => '72534111', 'email_reservas' => 'lapaz@chilis.com.bo',
                'instagram' => '@chilisbolivia', 'facebook_url' => 'facebook.com/ChilisBolivia',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:30',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '00:00',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=900',
                'logo_url' => 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Chili%27s_Grill_%26_Bar_logo_%282023%29.svg',
                'fecha_registro' => '2024-07-01', 'categorias' => ['Cocina Fusión'],
            ],
            [
                'nombre' => 'Dunkin\'',
                'descripcion' => 'Donuts, café y desayunos rápidos. La cadena favorita para empezar el día con energía.',
                'direccion' => 'Av. 6 de Agosto Nro. 2000, Sopocachi',
                'zona' => 'Sopocachi',
                'latitud' => -16.5080, 'longitud' => -68.1285,
                'telefono' => '72534112', 'email_reservas' => 'contacto@dunkinlapaz.com',
                'instagram' => '@dunkin_bolivia', 'facebook_url' => 'facebook.com/DunkinBolivia',
                'horario_apertura' => '07:00', 'horario_cierre' => '21:00',
                'hora_apertura_sabado' => '08:00', 'hora_cierre_sabado' => '22:00',
                'hora_apertura_domingo' => '08:00', 'hora_cierre_domingo' => '20:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900',
                'logo_url' => 'https://upload.wikimedia.org/wikipedia/commons/9/96/Dunkin%27_Donuts_logo.svg',
                'fecha_registro' => '2024-07-15', 'categorias' => ['Café y Brunch'],
            ],

            // ==================== REAL LOCAL RESTAURANTS (18) ====================
            [
                'nombre' => 'Gustu',
                'descripcion' => 'Restaurante de alta cocina boliviana de autor. Liderado por el chef Kamilla Seidler y Marsia Taha, con ingredientes nativos de Bolivia.',
                'direccion' => 'Calle 10 Nro. 300, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5380, 'longitud' => -68.0705,
                'telefono' => '72534113', 'email_reservas' => 'reservas@gustu.com.bo',
                'instagram' => '@gustu_bolivia', 'facebook_url' => 'facebook.com/GustuLaPaz',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:30',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-08-01', 'categorias' => ['Cocina Fusión', 'Comida Boliviana'],
            ],
            [
                'nombre' => 'Ali Pacha',
                'descripcion' => 'Primer restaurante vegano de alta cocina en Bolivia. Ingredientes orgánicos y ancestrales con técnicas contemporáneas.',
                'direccion' => 'Calle 21 Nro. 850, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5415, 'longitud' => -68.0730,
                'telefono' => '72534114', 'email_reservas' => 'info@alipacha.com',
                'instagram' => '@ali_pacha', 'facebook_url' => 'facebook.com/AliPachaRestaurante',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => null, 'hora_cierre_domingo' => null,
                'foto_portada' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-08-10', 'categorias' => ['Cocina Fusión'],
            ],
            [
                'nombre' => 'Popular Cocina Boliviana',
                'descripcion' => 'Auténtica cocina boliviana con recetas tradicionales reinterpretadas. Un homenaje a los sabores del altiplano y los valles.',
                'direccion' => 'Calle Sagárnaga Nro. 328',
                'zona' => 'Centro',
                'latitud' => -16.4955, 'longitud' => -68.1350,
                'telefono' => '72534115', 'email_reservas' => 'reservas@popularcocina.com',
                'instagram' => '@popularcocina', 'facebook_url' => 'facebook.com/PopularCocinaBoliviana',
                'horario_apertura' => '12:00', 'horario_cierre' => '21:30',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '22:00',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-08-20', 'categorias' => ['Comida Boliviana'],
            ],
            [
                'nombre' => 'Mi Chola',
                'descripcion' => 'Cocina boliviana contemporánea con un toque divertido y moderno. Homenaje a la chola paceña y su gastronomía.',
                'direccion' => 'Calle 20 Nro. 700, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5420, 'longitud' => -68.0725,
                'telefono' => '72534116', 'email_reservas' => 'hola@michola.com.bo',
                'instagram' => '@mi_chola_lapaz', 'facebook_url' => 'facebook.com/MiCholaRestaurante',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:30',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-09-01', 'categorias' => ['Comida Boliviana'],
            ],
            [
                'nombre' => 'Biofilia Café',
                'descripcion' => 'Café de especialidad con enfoque sostenible. Productos orgánicos, bowls saludables y un jardín vertical impresionante.',
                'direccion' => 'Calle 8 Nro. 150, Obrajes',
                'zona' => 'Zona Sur',
                'latitud' => -16.5320, 'longitud' => -68.0750,
                'telefono' => '72534117', 'email_reservas' => 'hola@biofilia.cafe',
                'instagram' => '@biofilia_cafe', 'facebook_url' => 'facebook.com/BiofiliaCafe',
                'horario_apertura' => '08:00', 'horario_cierre' => '21:00',
                'hora_apertura_sabado' => '09:00', 'hora_cierre_sabado' => '22:00',
                'hora_apertura_domingo' => '09:00', 'hora_cierre_domingo' => '20:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-09-10', 'categorias' => ['Café y Brunch'],
            ],
            [
                'nombre' => 'Brutal Burger',
                'descripcion' => 'Hamburguesas artesanales smash con carne angus. Papas bravas, chesse fries y milkshakes espectaculares.',
                'direccion' => 'Av. Montenegro Nro. 234, San Miguel',
                'zona' => 'Zona Sur',
                'latitud' => -16.5440, 'longitud' => -68.0760,
                'telefono' => '72534118', 'email_reservas' => 'pedidos@brutalburger.bo',
                'instagram' => '@brutalburger_lpz', 'facebook_url' => 'facebook.com/BrutalBurgerLaPaz',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '00:00',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-09-20', 'categorias' => ['Burgers'],
            ],
            [
                'nombre' => 'The Carrot Tree',
                'descripcion' => 'Café healthy con opciones vegetarianas y veganas. Bowls, ensaladas, smoothies y repostería natural.',
                'direccion' => 'Calle 15 Nro. 450, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5390, 'longitud' => -68.0715,
                'telefono' => '72534119', 'email_reservas' => 'info@thecarrottree.com',
                'instagram' => '@thecarrottree', 'facebook_url' => 'facebook.com/TheCarrotTreeLaPaz',
                'horario_apertura' => '08:30', 'horario_cierre' => '21:00',
                'hora_apertura_sabado' => '09:00', 'hora_cierre_sabado' => '22:00',
                'hora_apertura_domingo' => '09:00', 'hora_cierre_domingo' => '20:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-10-01', 'categorias' => ['Café y Brunch'],
            ],
            [
                'nombre' => 'The Steakhouse',
                'descripcion' => 'Carnes maduradas de primera calidad, cortes argentinos y parrilla boliviana. El paraíso de los amantes de la carne.',
                'direccion' => 'Av. Ballivián Nro. 600, San Miguel',
                'zona' => 'Zona Sur',
                'latitud' => -16.5460, 'longitud' => -68.0780,
                'telefono' => '72534120', 'email_reservas' => 'reservas@thesteakhouse.bo',
                'instagram' => '@thesteakhouse_lpz', 'facebook_url' => 'facebook.com/TheSteakhouseLaPaz',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '00:00',
                'hora_apertura_domingo' => '12:30', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-10-10', 'categorias' => ['Parrilla'],
            ],
            [
                'nombre' => 'Santo Ramen',
                'descripcion' => 'Ramen artesanal japonés con insumos locales. Caldos intensos, noodles frescos y gyozas espectaculares.',
                'direccion' => 'Calle 11 Nro. 200, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5370, 'longitud' => -68.0690,
                'telefono' => '72534121', 'email_reservas' => 'hola@santoramen.bo',
                'instagram' => '@santoramen_lpz', 'facebook_url' => 'facebook.com/SantoRamenLaPaz',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-10-20', 'categorias' => ['Cocina Fusión'],
            ],
            [
                'nombre' => 'Sach\'a Yuntas',
                'descripcion' => 'Cocina tradicional boliviana con productos orgánicos del altiplano y los valles. Sabores auténticos en cada plato.',
                'direccion' => 'Calle Linares Nro. 455',
                'zona' => 'Centro',
                'latitud' => -16.4940, 'longitud' => -68.1360,
                'telefono' => '72534122', 'email_reservas' => 'info@sachayuntas.com',
                'instagram' => '@sacha_yuntas', 'facebook_url' => 'facebook.com/SachaYuntasLP',
                'horario_apertura' => '11:30', 'horario_cierre' => '21:00',
                'hora_apertura_sabado' => '11:30', 'hora_cierre_sabado' => '21:30',
                'hora_apertura_domingo' => null, 'hora_cierre_domingo' => null,
                'foto_portada' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-10-25', 'categorias' => ['Comida Boliviana'],
            ],
            [
                'nombre' => 'Yati Bolivia',
                'descripcion' => 'Restaurante de cocina boliviana de autor que rescata ingredientes ancestrales como la quinua, cañahua y tarwi.',
                'direccion' => 'Calle 13 Nro. 560, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5385, 'longitud' => -68.0700,
                'telefono' => '72534123', 'email_reservas' => 'contacto@yati.bo',
                'instagram' => '@yati_bolivia', 'facebook_url' => 'facebook.com/YatiBolivia',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '22:30',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-11-01', 'categorias' => ['Comida Boliviana'],
            ],
            [
                'nombre' => 'Terra',
                'descripcion' => 'Cocina fusión latinoamericana con influencia boliviana. Platos coloridos, coctelería creativa y ambiente vibrante.',
                'direccion' => 'Calle 22 Nro. 120, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5435, 'longitud' => -68.0745,
                'telefono' => '72534124', 'email_reservas' => 'reservas@terralapaz.com',
                'instagram' => '@terra_restaurant_lpz', 'facebook_url' => 'facebook.com/TerraRestauranteLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:30',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-11-10', 'categorias' => ['Cocina Fusión'],
            ],
            [
                'nombre' => 'La Rufina',
                'descripcion' => 'Tradicional restaurante paceño especializado en platos típicos. Fricasé, chairo, plato paceño y mucho más.',
                'direccion' => 'Calle Mercado Nro. 1234',
                'zona' => 'Centro',
                'latitud' => -16.4970, 'longitud' => -68.1330,
                'telefono' => '72534125', 'email_reservas' => 'info@larufina.com',
                'instagram' => '@larufina_lpz', 'facebook_url' => 'facebook.com/LaRufinaRestaurante',
                'horario_apertura' => '11:00', 'horario_cierre' => '21:00',
                'hora_apertura_sabado' => '11:00', 'hora_cierre_sabado' => '21:30',
                'hora_apertura_domingo' => '11:00', 'hora_cierre_domingo' => '20:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-11-20', 'categorias' => ['Comida Boliviana'],
            ],
            [
                'nombre' => 'Yerba Buena',
                'descripcion' => 'Café y restaurante saludable con jardín interior. Platos vegetarianos, veganos y sin gluten. Smoothies y tés especiales.',
                'direccion' => 'Calle 7 Nro. 85, Obrajes',
                'zona' => 'Zona Sur',
                'latitud' => -16.5310, 'longitud' => -68.0740,
                'telefono' => '72534126', 'email_reservas' => 'hola@yerbabuena.bo',
                'instagram' => '@yerbabuena_lpz', 'facebook_url' => 'facebook.com/YerbaBuenaLP',
                'horario_apertura' => '08:30', 'horario_cierre' => '21:00',
                'hora_apertura_sabado' => '09:00', 'hora_cierre_sabado' => '22:00',
                'hora_apertura_domingo' => '09:00', 'hora_cierre_domingo' => '20:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-12-01', 'categorias' => ['Café y Brunch'],
            ],
            [
                'nombre' => 'Tinto',
                'descripcion' => 'Bar de vinos y tapas con más de 50 etiquetas nacionales e internacionales. Tablas de quesos y embutidos, ambiente sofisticado.',
                'direccion' => 'Calle 14 Nro. 300, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5395, 'longitud' => -68.0720,
                'telefono' => '72534127', 'email_reservas' => 'reservas@tintolapaz.com',
                'instagram' => '@tinto_bar_lpz', 'facebook_url' => 'facebook.com/TintoLaPaz',
                'horario_apertura' => '17:00', 'horario_cierre' => '00:00',
                'hora_apertura_sabado' => '17:00', 'hora_cierre_sabado' => '02:00',
                'hora_apertura_domingo' => null, 'hora_cierre_domingo' => null,
                'foto_portada' => 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-12-10', 'categorias' => ['Parrilla'],
            ],
            [
                'nombre' => 'ASAU',
                'descripcion' => 'Cocina fusión boliviano-japonesa con ingredientes nativos. Nikkei, robata y coctelería de autor.',
                'direccion' => 'Calle 19 Nro. 600, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5410, 'longitud' => -68.0735,
                'telefono' => '72534128', 'email_reservas' => 'info@asau.bo',
                'instagram' => '@asau_lapaz', 'facebook_url' => 'facebook.com/ASAULaPaz',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '00:00',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=900',
                'logo_url' => null,
                'fecha_registro' => '2024-12-20', 'categorias' => ['Cocina Fusión', 'Sushi'],
            ],
            [
                'nombre' => 'La Suisse',
                'descripcion' => 'Restaurante suizo con tradición en La Paz. Fondue, raclette, pastas artesanales y postres europeos.',
                'direccion' => 'Av. 6 de Agosto Nro. 2450',
                'zona' => 'Sopocachi',
                'latitud' => -16.5095, 'longitud' => -68.1290,
                'telefono' => '72534129', 'email_reservas' => 'reservas@lasuisse.bo',
                'instagram' => '@lasuisse_lpz', 'facebook_url' => 'facebook.com/LaSuisseLaPaz',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-01-05', 'categorias' => ['Pastas'],
            ],
            [
                'nombre' => 'Pronto Dalicatessen',
                'descripcion' => 'Delicatessen con productos importados y sándwiches gourmet. Tablas de quesos, vinos y cafés especiales.',
                'direccion' => 'Calle 8 Nro. 200, Obrajes',
                'zona' => 'Zona Sur',
                'latitud' => -16.5335, 'longitud' => -68.0760,
                'telefono' => '72534130', 'email_reservas' => 'info@prontodalicatessen.com',
                'instagram' => '@pronto_deli', 'facebook_url' => 'facebook.com/ProntoDalicatessen',
                'horario_apertura' => '09:00', 'horario_cierre' => '21:00',
                'hora_apertura_sabado' => '09:00', 'hora_cierre_sabado' => '22:00',
                'hora_apertura_domingo' => '10:00', 'hora_cierre_domingo' => '20:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-01-15', 'categorias' => ['Café y Brunch'],
            ],

            // ==================== CREATED RESTAURANTS (20) ====================
            [
                'nombre' => 'El Hornito',
                'descripcion' => 'Pizzería artesanal de horno de leña con masa madre de 48 horas. Ingredientes italianos importados y locales.',
                'direccion' => 'Calle 16 Nro. 450, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5400, 'longitud' => -68.0718,
                'telefono' => '72534131', 'email_reservas' => 'pedidos@elhornito.bo',
                'instagram' => '@elhornito_lpz', 'facebook_url' => 'facebook.com/ElHornitoPizza',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:30',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:30',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-01-25', 'categorias' => ['Pizza'],
            ],
            [
                'nombre' => 'Mochi Mochi',
                'descripcion' => 'Sushi bar creativo con rolls únicos y fusión nikkei. Ambiente moderno y acogedor en el corazón de la zona sur.',
                'direccion' => 'Av. Ballivián Nro. 780, San Miguel',
                'zona' => 'Zona Sur',
                'latitud' => -16.5450, 'longitud' => -68.0770,
                'telefono' => '72534132', 'email_reservas' => 'info@mochimochi.bo',
                'instagram' => '@mochimochi_lpz', 'facebook_url' => 'facebook.com/MochiMochiLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:30',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-02-01', 'categorias' => ['Sushi'],
            ],
            [
                'nombre' => 'Barbarian Burger',
                'descripcion' => 'Hamburguesas monumentales con ingredientes salvajes. Doble carne, cheddar, bacon y salsas secretas.',
                'direccion' => 'Calle 10 Nro. 550, Obrajes',
                'zona' => 'Zona Sur',
                'latitud' => -16.5340, 'longitud' => -68.0755,
                'telefono' => '72534133', 'email_reservas' => 'pedidos@barbarianburger.bo',
                'instagram' => '@barbarian_lpz', 'facebook_url' => 'facebook.com/BarbarianBurgerLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '00:00',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-02-10', 'categorias' => ['Burgers'],
            ],
            [
                'nombre' => 'Fogón Boliviano',
                'descripcion' => 'Parrilla boliviana con cortes de carne nacional e importados. Ambiente campestre con fogón central.',
                'direccion' => 'Av. Costanera Nro. 1200, Irpavi',
                'zona' => 'Zona Sur',
                'latitud' => -16.5480, 'longitud' => -68.0800,
                'telefono' => '72534134', 'email_reservas' => 'reservas@fogonboliviano.bo',
                'instagram' => '@fogon_boliviano', 'facebook_url' => 'facebook.com/FogonBolivianoLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:30',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '00:30',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-02-20', 'categorias' => ['Parrilla'],
            ],
            [
                'nombre' => 'La Casa del Pique',
                'descripcion' => 'Especialistas en pique macho, plato paceño y silpancho. Comida boliviana contundente y casera.',
                'direccion' => 'Calle Colón Nro. 567',
                'zona' => 'Centro',
                'latitud' => -16.4960, 'longitud' => -68.1345,
                'telefono' => '72534135', 'email_reservas' => 'contacto@lacasadelpique.bo',
                'instagram' => '@lacasadelpique', 'facebook_url' => 'facebook.com/LaCasaDelPique',
                'horario_apertura' => '11:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '11:00', 'hora_cierre_sabado' => '22:30',
                'hora_apertura_domingo' => '11:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-03-01', 'categorias' => ['Comida Boliviana'],
            ],
            [
                'nombre' => 'Café Origen',
                'descripcion' => 'Cafetería de especialidad que tuesta su propio grano boliviano. Catas, brunch y repostería artesanal.',
                'direccion' => 'Calle 6 Nro. 120, Obrajes',
                'zona' => 'Zona Sur',
                'latitud' => -16.5305, 'longitud' => -68.0730,
                'telefono' => '72534136', 'email_reservas' => 'hola@cafeorigen.bo',
                'instagram' => '@cafeorigen_bo', 'facebook_url' => 'facebook.com/CafeOrigenLP',
                'horario_apertura' => '08:00', 'horario_cierre' => '21:00',
                'hora_apertura_sabado' => '08:00', 'hora_cierre_sabado' => '22:00',
                'hora_apertura_domingo' => '09:00', 'hora_cierre_domingo' => '20:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-03-10', 'categorias' => ['Café y Brunch'],
            ],
            [
                'nombre' => 'Nonna Mia',
                'descripcion' => 'Pastas artesanales italianas hechas a mano. Ñoquis, fetuccinis, lasañas y salsas caseras como la nonna.',
                'direccion' => 'Calle 18 Nro. 350, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5408, 'longitud' => -68.0728,
                'telefono' => '72534137', 'email_reservas' => 'info@nonnamia.bo',
                'instagram' => '@nonnamia_lpz', 'facebook_url' => 'facebook.com/NonnaMiaLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '12:30', 'hora_cierre_domingo' => '21:30',
                'foto_portada' => 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-03-20', 'categorias' => ['Pastas'],
            ],
            [
                'nombre' => 'Pollos Real',
                'descripcion' => 'Pollo al spiedo con la receta secreta de la abuela. Acompañado de papas fritas, ensalada y salsas caseras.',
                'direccion' => 'Av. Del Poeta Nro. 789, Miraflores',
                'zona' => 'Miraflores',
                'latitud' => -16.4880, 'longitud' => -68.1260,
                'telefono' => '72534138', 'email_reservas' => 'pedidos@pollosreal.bo',
                'instagram' => '@pollosreal_lpz', 'facebook_url' => 'facebook.com/PollosRealLP',
                'horario_apertura' => '11:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '11:00', 'hora_cierre_sabado' => '22:30',
                'hora_apertura_domingo' => '11:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-04-01', 'categorias' => ['Pollos'],
            ],
            [
                'nombre' => 'Dragón Rojo',
                'descripcion' => 'Auténtica cocina chifa con recetas tradicionales peruano-chinas. Wantán, arroces, aeropuerto y tallarines.',
                'direccion' => 'Calle Buenos Aires Nro. 345',
                'zona' => 'Centro',
                'latitud' => -16.4925, 'longitud' => -68.1375,
                'telefono' => '72534139', 'email_reservas' => 'pedidos@dragonrojo.bo',
                'instagram' => '@dragonrojo_chifa', 'facebook_url' => 'facebook.com/DragonRojoChifa',
                'horario_apertura' => '11:30', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '11:30', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '21:30',
                'foto_portada' => 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-04-10', 'categorias' => ['Chifa'],
            ],
            [
                'nombre' => 'El Marino',
                'descripcion' => 'Pescados y mariscos frescos del Pacífico. Ceviches, parihuelas, juanes y arroces marineros.',
                'direccion' => 'Calle 5 Nro. 80, Obrajes',
                'zona' => 'Zona Sur',
                'latitud' => -16.5300, 'longitud' => -68.0725,
                'telefono' => '72534140', 'email_reservas' => 'reservas@elmarino.bo',
                'instagram' => '@elmarino_lpz', 'facebook_url' => 'facebook.com/ElMarinoLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-04-20', 'categorias' => ['Mariscos'],
            ],
            [
                'nombre' => 'Dulce Tentación',
                'descripcion' => 'Pastelería fina con tortas decoradas, macarons, cheesecakes y helados artesanales. El paraíso del postre.',
                'direccion' => 'Calle 12 Nro. 400, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5375, 'longitud' => -68.0695,
                'telefono' => '72534141', 'email_reservas' => 'pedidos@dulcetentacion.bo',
                'instagram' => '@dulcetentacion_lpz', 'facebook_url' => 'facebook.com/DulceTentacionLP',
                'horario_apertura' => '09:00', 'horario_cierre' => '21:00',
                'hora_apertura_sabado' => '09:00', 'hora_cierre_sabado' => '22:00',
                'hora_apertura_domingo' => '10:00', 'hora_cierre_domingo' => '20:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-05-01', 'categorias' => ['Postres y Panadería'],
            ],
            [
                'nombre' => 'Ñami Fusión',
                'descripcion' => 'Cocina de autor que fusiona sabores bolivianos con técnicas asiáticas y europeas. Una explosión de sabores.',
                'direccion' => 'Calle 23 Nro. 180, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5440, 'longitud' => -68.0750,
                'telefono' => '72534142', 'email_reservas' => 'reservas@namifusion.bo',
                'instagram' => '@namifusion_lpz', 'facebook_url' => 'facebook.com/NamiFusionLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '00:00',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-05-10', 'categorias' => ['Cocina Fusión'],
            ],
            [
                'nombre' => 'Napoli D\'Oro',
                'descripcion' => 'Pizza napolitana tradicional con ingredientes importados de Italia. Masa fina, mozzarella di bufala y horno de piedra.',
                'direccion' => 'Calle 9 Nro. 250, Obrajes',
                'zona' => 'Zona Sur',
                'latitud' => -16.5345, 'longitud' => -68.0765,
                'telefono' => '72534143', 'email_reservas' => 'pedidos@napolidoro.bo',
                'instagram' => '@napolidoro_lpz', 'facebook_url' => 'facebook.com/NapoliDoroLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:30',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:30',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://upload.wikimedia.org/wikipedia/commons/9/91/Pizza-3007395.jpg',
                'logo_url' => null,
                'fecha_registro' => '2025-05-20', 'categorias' => ['Pizza'],
            ],
            [
                'nombre' => 'Samurai Ramen',
                'descripcion' => 'Ramen y cocina japonesa auténtica. Tonkotsu, shoyu, miso ramen, gyozas, yakitoris y sake.',
                'direccion' => 'Av. Montenegro Nro. 890, San Miguel',
                'zona' => 'Zona Sur',
                'latitud' => -16.5465, 'longitud' => -68.0790,
                'telefono' => '72534144', 'email_reservas' => 'info@samurairamen.bo',
                'instagram' => '@samurai_ramen_lpz', 'facebook_url' => 'facebook.com/SamuraiRamenLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '13:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-06-01', 'categorias' => ['Cocina Fusión', 'Sushi'],
            ],
            [
                'nombre' => 'El Rancho',
                'descripcion' => 'Parrilla campestre con carnes maduradas y embutidos artesanales. Ambiente rústico con vista a la ciudad.',
                'direccion' => 'Av. Costanera Nro. 2000, Irpavi',
                'zona' => 'Zona Sur',
                'latitud' => -16.5500, 'longitud' => -68.0820,
                'telefono' => '72534145', 'email_reservas' => 'reservas@elrancho.bo',
                'instagram' => '@elrancho_parrilla', 'facebook_url' => 'facebook.com/ElRanchoLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '23:30',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '00:30',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-06-10', 'categorias' => ['Parrilla'],
            ],
            [
                'nombre' => 'Café La Paz',
                'descripcion' => 'Cafetería tradicional paceña con más de 30 años de historia. Café boliviano, pastelitos y salteñas.',
                'direccion' => 'Av. 16 de Julio Nro. 1800, El Prado',
                'zona' => 'Centro',
                'latitud' => -16.4975, 'longitud' => -68.1348,
                'telefono' => '72534146', 'email_reservas' => 'contacto@cafelapaz.bo',
                'instagram' => '@cafe_lapaz', 'facebook_url' => 'facebook.com/CafeLaPazLP',
                'horario_apertura' => '07:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '07:00', 'hora_cierre_sabado' => '22:30',
                'hora_apertura_domingo' => '08:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
                'logo_url' => null,
                'fecha_registro' => '2025-06-20', 'categorias' => ['Café y Brunch', 'Comida Boliviana'],
            ],
            [
                'nombre' => 'Pan Artesano',
                'descripcion' => 'Panadería artesanal con masa madre y harinas orgánicas. Croissants, sourdough, bollería y café de especialidad.',
                'direccion' => 'Calle 14 Nro. 500, Calacoto',
                'zona' => 'Zona Sur',
                'latitud' => -16.5398, 'longitud' => -68.0722,
                'telefono' => '72534147', 'email_reservas' => 'hola@panartesano.bo',
                'instagram' => '@panartesano_lpz', 'facebook_url' => 'facebook.com/PanArtesanoLP',
                'horario_apertura' => '07:30', 'horario_cierre' => '20:00',
                'hora_apertura_sabado' => '08:00', 'hora_cierre_sabado' => '21:00',
                'hora_apertura_domingo' => '08:00', 'hora_cierre_domingo' => '19:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-07-01', 'categorias' => ['Postres y Panadería', 'Café y Brunch'],
            ],
            [
                'nombre' => 'La Perla del Pacífico',
                'descripcion' => 'Cevichería peruano-boliviana con productos frescos del mar. Ceviches, tiraditos, pulpo al olivo y parihuelas.',
                'direccion' => 'Calle 7 Nro. 300, Obrajes',
                'zona' => 'Zona Sur',
                'latitud' => -16.5320, 'longitud' => -68.0745,
                'telefono' => '72534148', 'email_reservas' => 'reservas@laperladelpacifico.bo',
                'instagram' => '@laperla_pacifico', 'facebook_url' => 'facebook.com/LaPerlaDelPacificoLP',
                'horario_apertura' => '12:00', 'horario_cierre' => '22:00',
                'hora_apertura_sabado' => '12:00', 'hora_cierre_sabado' => '23:00',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-07-10', 'categorias' => ['Mariscos'],
            ],
            [
                'nombre' => 'Sabores del Oriente',
                'descripcion' => 'Cocina típica del oriente boliviano. Majao, locro, pacumutos, masaco y sopa de maní. Ambiente selvático.',
                'direccion' => 'Calle Linares Nro. 234',
                'zona' => 'Centro',
                'latitud' => -16.4935, 'longitud' => -68.1355,
                'telefono' => '72534149', 'email_reservas' => 'info@saboresdeloriente.bo',
                'instagram' => '@sabores_del_oriente', 'facebook_url' => 'facebook.com/SaboresDelOrienteLP',
                'horario_apertura' => '11:30', 'horario_cierre' => '21:30',
                'hora_apertura_sabado' => '11:30', 'hora_cierre_sabado' => '22:00',
                'hora_apertura_domingo' => '11:30', 'hora_cierre_domingo' => '21:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-07-20', 'categorias' => ['Comida Boliviana'],
            ],
            [
                'nombre' => 'Wok & Roll',
                'descripcion' => 'Chifa fusión con wok al momento. Tallarines saltados, arroz chaufa, wantán frito y dim sum tradicional.',
                'direccion' => 'Av. Ballivián Nro. 1000, San Miguel',
                'zona' => 'Zona Sur',
                'latitud' => -16.5470, 'longitud' => -68.0795,
                'telefono' => '72534150', 'email_reservas' => 'pedidos@wokandroll.bo',
                'instagram' => '@wokandroll_lpz', 'facebook_url' => 'facebook.com/WokAndRollLP',
                'horario_apertura' => '11:30', 'horario_cierre' => '22:30',
                'hora_apertura_sabado' => '11:30', 'hora_cierre_sabado' => '23:30',
                'hora_apertura_domingo' => '12:00', 'hora_cierre_domingo' => '22:00',
                'foto_portada' => 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=900',
                'logo_url' => null,
                'fecha_registro' => '2025-08-01', 'categorias' => ['Chifa'],
            ],
        ];
    }
}
